version: "3.6"

services:
    php:
        container_name: iproj_php
        build: 
            context: .
            dockerfile: .docker/php/dockerfile
        ports:
            - "9000:9000"
            - "80:80"
        depends_on:
            - db
    db:
        container_name: iproj_db
        build: 
            context: .
            dockerfile: .docker/mssql/dockerfile
        restart: always
        ports:
            - "1433:1433"