FROM mcr.microsoft.com/mssql/server:2019-latest

ENV SA_PASSWORD Bam1schijf
ENV ACCEPT_EULA Y
ENV MSSQL_PID Express

USER root

RUN mkdir -p /usr/src/app/scripts

COPY ./.docker/mssql/setup.sql /usr/src/app/scripts
COPY ./.docker/mssql/import-data.sh /usr/src/app/scripts
COPY ./.docker/mssql/entrypoint.sh /usr/src/app/scripts

RUN chmod +x /usr/src/app/scripts/*.sh

EXPOSE 1433

USER mssql
ENTRYPOINT /bin/bash /usr/src/app/scripts/entrypoint.sh

HEALTHCHECK --interval=10s --timeout=1s --start-period=2s --retries=5 \
	CMD /bin/bash /usr/src/app/scripts/import-data.sh || exit 1

